from __future__ import annotations


TOOLS = [
    {
        "id": "photo_naturalize",
        "name": "Naturalize Photo",
        "project": "Photography Tools",
        "category": "image",
        "ui": "photo_naturalize",
        "allowed_types": ["image"],
        "description": "Riduzione rumore e sharpen per una o piu immagini.",
        "multi_file": True,
        "params": [
            {"name": "mode", "type": "select", "default": "definitive", "options": ["definitive", "test"]},
            {"name": "denoise", "type": "number", "default": 1.4},
            {"name": "sharpen", "type": "number", "default": 1.4},
            {"name": "probe_margin", "type": "number", "default": 0.1},
            {"name": "test_crops", "type": "boolean", "default": False},
        ],
    },
    {
        "id": "stereo_overlay",
        "name": "Stereo Overlay",
        "project": "StereoImage",
        "category": "image",
        "ui": "stereo_overlay",
        "allowed_types": ["image"],
        "description": "Allinea e fonde due immagini con punti scelti a mano.",
        "multi_file": False,
        "params": [
            {"name": "left_path", "type": "file", "required": True},
            {"name": "right_path", "type": "file", "required": True},
            {"name": "left_point", "type": "text", "placeholder": "x,y", "required": True},
            {"name": "right_point", "type": "text", "placeholder": "x,y", "required": True},
            {"name": "mode", "type": "select", "default": "alpha", "options": ["alpha", "add", "diff"]},
            {"name": "alpha", "type": "number", "default": 0.5},
        ],
    },
    {
        "id": "video_extract_frames",
        "name": "Extract Video Frames",
        "project": "Video Capture",
        "category": "video",
        "ui": "video_capture",
        "allowed_types": ["video"],
        "description": "Estrae frame da un intervallo video con ROI opzionale.",
        "multi_file": False,
        "params": [
            {"name": "video_path", "type": "file", "required": True},
            {"name": "start_time", "type": "number", "default": 0},
            {"name": "end_time", "type": "number", "default": 3},
            {"name": "roi", "type": "text", "placeholder": "x,y,w,h"},
            {"name": "remove_blurry", "type": "boolean", "default": False},
            {"name": "keep_best", "type": "number", "default": 0},
        ],
    },
    {
        "id": "video_make_gif",
        "name": "Create GIF",
        "project": "Video Capture",
        "category": "video",
        "ui": "video_capture",
        "allowed_types": ["video"],
        "description": "Crea una GIF da un intervallo video con ROI opzionale.",
        "multi_file": False,
        "params": [
            {"name": "video_path", "type": "file", "required": True},
            {"name": "start_time", "type": "number", "default": 0},
            {"name": "end_time", "type": "number", "default": 3},
            {"name": "roi", "type": "text", "placeholder": "x,y,w,h"},
            {"name": "make_optimized", "type": "boolean", "default": True},
        ],
    },
    {
        "id": "video_convert_web",
        "name": "Convert Video For Web",
        "project": "Video Capture",
        "category": "video",
        "ui": "video_convert_web",
        "allowed_types": ["video"],
        "description": "Conversione video web compatibile stile Video Capture.",
        "multi_file": True,
        "params": [
            {"name": "force", "type": "boolean", "default": False},
        ],
    },
    {
        "id": "gopro_convert",
        "name": "GoPro Converter",
        "project": "Gopro Exporter",
        "category": "video",
        "ui": "gopro_convert",
        "allowed_types": ["video"],
        "description": "Ricodifica un video con ffmpeg e risoluzione target.",
        "multi_file": False,
        "params": [
            {"name": "video_path", "type": "file", "required": True},
            {"name": "resolution", "type": "text", "default": "1080"},
            {"name": "codec", "type": "text", "default": "libx264"},
            {"name": "crf", "type": "number", "default": 23},
            {"name": "preset", "type": "text", "default": "medium"},
        ],
    },
    {
        "id": "bird_audio_batch",
        "name": "Bird Audio Batch",
        "project": "Bird Audio",
        "category": "audio",
        "ui": "bird_audio_batch",
        "allowed_types": ["audio"],
        "description": "Analizza uno o piu file audio con BirdNET.",
        "multi_file": True,
        "params": [
            {"name": "lat", "type": "number", "default": 45.65423642845939},
            {"name": "lon", "type": "number", "default": 13.812502298723128},
            {"name": "min_confidence", "type": "number", "default": 0.7},
            {"name": "export_clips", "type": "boolean", "default": True},
            {"name": "clip_span", "type": "select", "default": "detection", "options": ["detection", "from_detection", "full_slice"]},
        ],
    },
    {
        "id": "bird_audio_denoise",
        "name": "Bird Audio Denoise",
        "project": "Bird Audio",
        "category": "audio",
        "ui": "bird_audio_denoise",
        "allowed_types": ["audio"],
        "description": "Pulisce un WAV con il denoiser del progetto audio.",
        "multi_file": False,
        "params": [
            {"name": "audio_path", "type": "file", "required": True},
            {"name": "high_pass_hz", "type": "number", "default": 500},
            {"name": "noise_reduction_factor", "type": "number", "default": 2.0},
        ],
    },
    {
        "id": "bird_audio_live",
        "name": "Bird Audio Live",
        "project": "Bird Audio",
        "category": "audio",
        "ui": "bird_audio_live",
        "allowed_types": [],
        "browser_ready": True,
        "description": "Ascolto live da microfono con worker interno dedicato.",
        "multi_file": False,
        "params": [
            {"name": "action", "type": "select", "default": "start", "options": ["start", "status", "stop"]},
            {"name": "backend", "type": "select", "default": "sounddevice", "options": ["sounddevice", "pvrecorder", "auto"]},
            {"name": "device_index", "type": "number", "default": 17},
            {"name": "min_confidence", "type": "number", "default": 0.1},
            {"name": "frame_length", "type": "number", "default": 512},
            {"name": "slice_interval", "type": "number", "default": 300},
            {"name": "disable_denoise", "type": "boolean", "default": True},
            {"name": "verbose", "type": "boolean", "default": True},
        ],
    },
]
